### PR TITLE
Restructure Jekyll work for GitHub pages

### PR DESCRIPTION
**Pull request by nottrobin**
This moves jekyll files to the `/docs` folder, as that's [the only subfolder GitHub will accept](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch).

It also restructures the Jekyll files slightly, and moves the actual documentation to `/docs/src`

Once this is merged, <https://ubuntudesign.github.io/vanilla-framework> should look truly beautiful.

QA
---

You can see an example of how this works on GitHub pages at <https://nottrobin.github.io/vanilla-framework/>.

To try it locally, pull down the code and run:

``` bash
bundle install
npm install
gulp jekyll
```

Then browse to <http://127.0.0.1:4000/vanilla-framework/>.

### CODE REVIEW

**Comment by nottrobin** [comment]
The MD files aren't part of the Jekyll stuff. They're the actual documentation, to be pulled into the docs site. The natural place for them to live is /docs. But thanks to GitHub, the Jekyll files have to live at /docs, so they can't live there. Given that, I don't know where to put them. But in a sense they are documentation source files - they will get built to real documentation HTML by document tation-builder. But if you prefer another structure please suggest one. Maybe a "/documentation" folder alongside the "/docs" one? But that's also confusing. "/docs/markdown"?

**Comment by nottrobin** [comment]
Or we could keep all Jekyll files at top level

**Comment by nottrobin** [comment]
@anthonydillon now I'm no longer sure that's the best structure. The docs should be easy to find. If you download the codebase and that's all you have, the documentation should be fairly easy to discover.

Can you think of a more obvious structure, working within the confines of GitHub Pages + Jekyll?

**Comment by anthonydillon** [comment]
Not sure, we had a couple of ideal approaches from the sprint [1].

Robin would you mind joining the Vanilla stand up so we could frame the
discuss. May need a quick meeting to iron this out.

[1] Ideal approaches:
- three folders at the top directory. `/sass/_patterns_button.scss`,
`/docs/patterns/button.md` and `/examples/patterns/button.html`
- have three files inside each component directory
`/components/patterns/button/button.scss`, `/components/patterns/button/
doc.md` and `/components/patterns/button/example.html`

**Comment by anthonydillon** [comment]
Linked https://github.com/ubuntudesign/vanilla-framework/issues/803

**Comment by nottrobin** [comment]
I think I prefer [this structure](https://github.com/ubuntudesign/vanilla-framework/pull/816) (see discussion in https://github.com/ubuntudesign/vanilla-framework/issues/803)

**Comment by nottrobin** [comment]
Closing this - we're going with #816 instead

**Pull request closed without merging**
