### PR TITLE
./run script to run node commands (e.g.: gulp) inside a docker container to manage dependencies

### PR DESCRIPTION
**Pull request by nottrobin**
This means you don't need to install NPM, or node, or worry about which versions of these you have.

You also don't need to worry about doing `npm install` - the docker image will detect whether packages are up-to-date and re-install if anything has changed.

The only dependency is docker. Try it out.

QA
---

Try:

``` bash
./run -h
./run usage
./run gulp
./run gulp test
./run gulp build
./run gulp watch
```

### CODE REVIEW

**Comment by barrymcgee** [comment]
@nottrobin I tried running `./run -h` a few time and each time my machine hangs here:

```bash
npm info retry fetch attempt 1 at 9:50:27 AM
npm info attempt registry request try #1 at 9:50:27 AM
npm http fetch GET https://registry.npmjs.org/ua-parser-js/-/ua-parser-js-0.7.10.tgz
npm http 200 https://registry.npmjs.org/serve-index
npm http fetch 200 https://registry.npmjs.org/server-destroy/-/server-destroy-1.0.1.tgz
npm http fetch 200 https://registry.npmjs.org/ua-parser-js/-/ua-parser-js-0.7.10.tgz
npm info retry fetch attempt 1 at 9:50:27 AM
npm info attempt registry request try #1 at 9:50:27 AM
npm http fetch GET https://registry.npmjs.org/socket.io/-/socket.io-1.4.8.tgz
npm info retry fetch attempt 1 at 9:50:27 AM
npm info attempt registry request try #1 at 9:50:27 AM
npm http fetch GET https://registry.npmjs.org/rx/-/rx-4.1.0.tgz
npm http fetch 200 https://registry.npmjs.org/socket.io/-/socket.io-1.4.8.tgz
npm info retry fetch attempt 1 at 9:50:27 AM
npm info attempt registry request try #1 at 9:50:27 AM
npm http fetch GET https://registry.npmjs.org/yargs/-/yargs-5.0.0.tgz
npm http fetch 200 https://registry.npmjs.org/rx/-/rx-4.1.0.tgz
npm info retry fetch attempt 1 at 9:50:27 AM
npm info attempt registry request try #1 at 9:50:27 AM
npm http fetch GET https://registry.npmjs.org/serve-index/-/serve-index-1.8.0.tgz
npm http fetch 200 https://registry.npmjs.org/yargs/-/yargs-5.0.0.tgz
npm http fetch 200 https://registry.npmjs.org/serve-index/-/serve-index-1.8.0.tgz
[      ............] - fetchMetadata: http fetch 200 https://registry.npmjs.org/serve-index/-/serve-index-1.8.0.tgz
```

One of my initial concerns here is that most developers understand and have npm installed on their machines - are you raising the barrier of use by forcing them to install and use Docker?

**Comment by barrymcgee** [comment]
Update.. it did eventually all install, it took a very long time on a very fast connection.. concern?

**Comment by nottrobin** [comment]
`npm install` always takes a very long time to install. I think maybe you haven't reinstalled NPM modules for a while.

**Comment by barrymcgee** [comment]
@nottrobin I'm happy to land this if you are?

**Comment by nottrobin** [comment]
@barrymcgee yes I'm happy for you to merge it. My only reservation was about whether we change the readme, but I guess that can be considered outside of the scope of this PR, so if it needs to change it can be a new piece of work.

**Pull request merged**
