### PR TITLE
Introducing sass lint

### PR DESCRIPTION
**Pull request by nottrobin**
Replace `gulp-scss-lint`, which requires Ruby's `scss-lint` tool to be installed locally, with `gulp-sass-lint`, which uses the purely node-based `sass-lint`.

## Differences

Many of the rules in `scss-lint` have direct equivalents in `sass-lint`. Where there aren't direct equivalents, there are similar rules which work just as well or better - For example, I've replaced the old `CapitalizationInSelector` rule with `class-name-format`, which will enforce BEM class names.

The one important feature in `scss-lint` which is missing in `sass-lint` is the ability to ignore specific rules for individual blocks of code with control comments. This feature [is coming to sass-lint](https://github.com/sasstools/sass-lint/pull/677). The only place where we need this is for ignoring the `no-important` rule in utility classes. Therefore, I've ~~simply left `no-important` at the "warning" level~~ turned off `no-important` for now, and hopefully we can enable it in the future when that PR is merged.

## Rules

I've gone through each rule in sass-lint and turned on every one that I thought made sense which didn't break our code-base. If it was trivial to fix the codebase to pass the rule, I've fixed the codebase. Where the fix wasn't trivial, I've simply left the check at the "warning" level, rather than making it strictly required. There are also some rules I've simply disabled as I don't think we want them.

### Disabled rules

- [no-attribute-selectors](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/no-attribute-selectors.md): We use many attribute selectors, and I think we need them
- [no-color-hex](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/no-color-hex.md): We need to use hexadecimal colours
- [no-disallowed-properties](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/no-disallowed-properties.md): I can't think of properties we want to explicitly disallow right now.
- [no-extends](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/no-extends.md): We use extends.
- [no-warn](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/no-warn.md): I don't see what's wrong with using the `@warn` function.
- [property-units](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/property-units.md): Disable specific units. I haven't defined any yet.
- [force-attribute-nesting](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/force-attribute-nesting.md): That is odd.
- [force-element-nesting](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/force-element-nesting.md): This one is just horrible
- [force-pseudo-nesting](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/force-pseudo-nesting.md): As above
- [id-name-format](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/id-name-format.md): We don't use IDs
- [shorthand-values](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/shorthand-values.md): I think shorthand values are often confusing and should not be enforced
- [no-important](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/no-important.md): As previously mentioned, utility classes have many `!important` overrides. I was gonna make this a warning, but it does make the warnings quite noise. Disabled at @barrymcgee's request, just until we get the ability to set `no-important` on a case-by-case basis for utility classes.
- [no-combinators](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/no-combinators.md): Disabled at @barrymcgee's request, as `+` et al. are perfectly valid selectors.

### Warnings

These are rules which would ideally be strict but it's too difficult to make that happen right now. Hopefully this will still encourage us to write better code.

- [no-universal-selectors](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/no-universal-selectors.md): Ideally we wouldn't need universal selectors outside of the reset...
- [placeholder-in-extend](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/placeholder-in-extend.md): All extends should be placeholders (but we have done it on classes in many places)
- [no-color-literals](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/no-color-literals.md): Ideally all colours would be defined in variables
- [no-combinators](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/no-combinators.md): It would be nice if all our CSS was clean enough that we didn't need complex selectors
- [no-transition-all](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/no-transition-all.md): Ideally our transitions should be explicit.
- [no-universal-selectors](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/no-universal-selectors.md): Ideally we wouldn't need these outside the reset
- [no-vendor-prefixes](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/.md): Ideally we don't need these either. But we do in a couple of places for special browser-specific rules. Hopefully in future this rule will become more intelligent and we can deliberately allow the rules we really need.
- [variable-for-property](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/variable-for-property.md): I can't think of any properties to enforce variables for right now.
- [property-sort-order](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/property-sort-order.md): Made into a warning at the request of @WillMoggridge et al.

### Strict rules

Here is the list of strict rules that will now be enforced:

- [class-name-format](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/class-name-format.md): Ensure hyphenated BEM class names
- [extends-before-mixins](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/extends-before-mixins.md): Extends should go at the top
- [extends-before-declarations](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/extends-before-declarations.md): Ditto
- [mixins-before-declarations](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/mixins-before-declarations.md): Mixing should go just below Extends
- [no-color-keywords](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/no-color-keywords.md): Don't use colour keywords (e,g, `white`)
- [no-css-comments](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/no-css-comments.md): No CSS-style comments (e.g. `/* comment */`)
- [no-debug](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/no-debug.md): `@debug` statements aren't allowed in committed code
- [no-duplicate-properties](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/no-duplicate-properties.md)
- [no-empty-rulesets](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/no-empty-rulesets.md)
- [no-invalid-hex](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/no-invalid-hex.md): Check hex colour codes for validity (3 or 6 chars, etc.)
- [no-mergeable-selectors](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/no-mergeable-selectors.md): More intellegent de-duping
- [no-misspelled-properties](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/no-misspelled-properties.md)
- [no-trailing-whitespace](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/no-trailing-whitespace.md)
- [no-trailing-zero](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/no-trailing-zero.md): Remove extra zeros behind decimal points in numbers
- [no-url-protocols](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/no-url-protocols.md): No linking to 3rd party resources
- [one-declaration-per-line](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/one-declaration-per-line.md)
- [empty-line-between-blocks](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/empty-line-between-blocks.md)
- [single-line-per-selector](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/single-line-per-selector.md)
- [no-ids](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/no-ids.md)
- [no-qualifying-elements](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/no-qualifying-elements.md): Don't allow element selectors before classes
- [function-name-format](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/function-name-format.md): Check function names are "hyphenatedlowercase"
- [mixin-name-format](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/mixin-name-format.md): Same for mixins
- [placeholder-name-format](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/placeholder-name-format.md): Same for placeholders
- [variable-name-format](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/variable-name-format.md): Same for variable names
- [attribute-quotes](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/attribute-quotes.md): Must use quotes in attribute selectors (`[lang="en"]`)
- [bem-depth](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/bem-depth.md): Don't allow chained elements in BEM class names (`block__element__element__element`)
- [border-zero](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/border-zero.md): Use `0` for removing borders, over `none`
- [brace-style](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/brace-style.md): Ensure braces directly follow selectors, without a newline (`.selector {`)
- [clean-import-paths](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/clean-import-paths.md): Make sure `@import` statements stay clean
- [empty-args](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/empty-args.md): Don't use brackets unless necessary (`@import my-function;`)
- [hex-length](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/hex-length.md): Use the shortest hex colour value possible (`#abc` not `#aabbcc`)
- [hex-notation](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/hex-notation.md): Hex values always lowercase
- [indentation](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/indentation.md): Check indentation is consistently 2 spaces
- [leading-zero](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/leading-zero.md): Remove extra zeros before numbers (`.2` over `0.2`)
- [nesting-depth](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/nesting-depth.md): Don't allow nesting selectors more than 2 deep
- [pseudo-element](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/pseudo-element.md): Pseudo elements must have 2 colons, pseudo selectors must have one (`&:first-child, &::after`)
- [url-quotes](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/url-quotes.md): URLs should always have quotes around them
- [zero-unit](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/zero-unit.md): Never put units when setting properties to `0`
- [space-after-comma](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/space-after-comma.md)
- [space-before-colon](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/space-before-colon.md)
- [space-after-colon](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/space-after-colon.md)
- [space-before-brace](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/space-before-brace.md)
- [space-before-bang](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/space-before-bang.md)
- [space-after-bang](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/space-after-bang.md)
- [space-between-parens](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/space-between-parens.md)
- [space-around-operator](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/space-around-operator.md)
- [trailing-semicolon](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/trailing-semicolon.md)
- [final-newline](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/final-newline.md): Files should always end with a newline
- [quotes](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/quotes.md): Made strict at the request of @WillMoggridge et al.

## QA

To test this, simply run:

``` bash
gulp test
gulp build
```

You should see 257 warnings, but no errors.

### CODE REVIEW

**Comment by WillMoggridge** [comment]
I do think that linting on rule order and quote style is a great idea, even as just a warning.
It tidies things up and keeps a consistent style. In the same way as choosing a consistent indent level.

I feel linting sort order is one of the best uses for sass linting.

**Comment by anthonydillon** [comment]
Sounds good to me but I also think as there are setting a lint we should select a quote type.

**Comment by barrymcgee** [comment]
This is great work - output is much cleaner also.

- What the rationale for using `no-combinators`? It can be very useful to ensure styles don't cascade.
- Until the ability to disable rules within a file or section of the file, we should disable `no-important` given it's so prevalent and will pollute the output until then.
- I think we should enforce quotes one way or the other for consistency.
- I also like the idea of enforcing source order of selectors alphabetically or similar.

**Comment by nottrobin** [comment]
et tu @anthonydillon? Well it seems I may be overruled. I'm happy to enforce a quote format if you want.

@WillMoggridge:
As for sort order - I thought we had a split opinion one what the sort order should be anyway? I know some people like alphabetical - I thought others had other ideas? But if not, then sure we can enable it at the warning level.

@barrymcgee:
1. My rationale for `no-combinators` was just that CSS should be as simple as possible, so warning you when it's not quite so simple seems like a good idea. But on the other hand I'm not at all saying that the `+` selector is a bad thing to use. So I'm happy to disable this.
2. That's fine I'll turn off `no-important`
3. I'll get this done too
4. I think we should wait for more opinion from @deadlight and @richmccartney on which sort order

**Comment by nottrobin** [comment]
@barrymcgee, @WillMoggridge, @anthonydillon I've actionificated all those changes. Could all y'all confirm that everything is now awesome?

@deadlight, @richmccartney, @grahambancroft, @pmahnke your opinions please.

**Comment by nottrobin** [comment]
As an aside, the `sass-lint` command-line tool provides a `max-warnings` option, which is pretty cool - this would allow us to make the build break if the number of warnings was increased - meaning if you trigger a new warning you have to, at the very least, go and fix a different one.

However, currently you can't set `max-warnings` when using `gulp-sass-lint`, or through the `.sass-lint.yml` config file. Luckily, your friendly neighbourhood @nottrobin has submitted an [issue](https://github.com/sasstools/sass-lint/issues/856) and [pull request](https://github.com/sasstools/sass-lint/pull/857) to get this fixed.

**Comment by barrymcgee** [comment]
@nottrobin All looks good to me.. I've made a couple of improvements to fix property sort order linting errors but can't push to your branch - maybe that's not possible?

**Comment by nottrobin** [comment]
@barrymcgee I don't think that's possible. You can propose your own PR into
my branch (PRception) or you could just paste the diff into a paste bin for
me and I'll apply it manually.

**Comment by barrymcgee** [comment]
@nottrobin Not to worry then... I'm happy to land this now if you are?

**Pull request merged**
