### PR TITLE
Add Embedded Media util

### LINKED ISSUE #428: Audit utility .video-container
This should be deprecated as responsive media is a tool defined further up the cascade.

### PR DESCRIPTION
**Pull request by barrymcgee**
## Done

- Added embedded media util
- Deleted redundant helper classes
- Cleaned up naming of utils for consistency
- Added `.u-embedded-media` to replace `.video-container`

## QA

- Sanity check code
- Run code and along side pattern library 
- Check that example Youtube vid displays correctly across breakpoints.

## Details

Fixes #428, #393

### CODE REVIEW

**Comment by anthonydillon** [comment]
Code looks good :+1:

**Comment by anthonydillon** [comment]
Found a QA issue. The YouTube video is not responsive which is the main use of the util. Also vf.io is not responsive:
embedded media vanilla framework

**Comment by barrymcgee** [comment]
I have addressed the QA bug here - the demo had the wrong class. 

I've also updated vf.io to be responsive in https://github.com/ubuntudesign/vanillaframework.io/pull/11

**Comment by anthonydillon** [comment]
Perfect in conjunction with https://github.com/ubuntudesign/vanillaframework.io/pull/11 QA :+1:

**Pull request merged**
