### PR TITLE
Add gitter integration to travis

### PR DESCRIPTION
**Pull request by nottrobin**
QA
--

Check gitter - maybe it will have posted something in there?
https://gitter.im/ubuntudesign/vanilla-framework

### CODE REVIEW

**Comment by 0atman** [comment]
Awesome! Look good to me :+1:

**Comment by 0atman** [comment]
I didn't test, sorry. :-1:

**Comment by deadlight** [comment]
Oh 0atman :-1:

**Comment by nottrobin** [comment]
How now brown cow? (@0atman)

**Pull request merged**
