### PR TITLE
Lint footer scss

### PR DESCRIPTION
**Pull request by barrymcgee**
## Done

- Lint footer pattern by re-ordering sort order

## QA

- Check code
- Check pattern in vf.io

### CODE REVIEW

**Comment by anthonydillon** [comment]
LGTM 👍

**Comment by anthonydillon** [comment]
Not merging as design review required.

**Comment by barrymcgee** [comment]
Does it need a review if I didn't change any CSS, just re-ordered source order to satisfy linter?

**Comment by deadlight** [comment]
Yeah, I can see no possibility of visual changes from this commit and I've also double-checked the code. Removing the design review requirement and merging.

**Pull request merged**
