### PR TITLE
Add align-vertically helper

### PR DESCRIPTION
**Pull request by grahambancroft**
# Done
Add align-vertically helper

## QA
Run gulp build, pop on over to demo/index.html and have a lookie at .align-vertically there in the helper section.

## Details
Card: https://canonical.leankit.com/Boards/View/111185042/115594581

### CODE REVIEW

**Comment by anthonydillon** [comment]
We need to be able to use align-vertically without relying on equal heights. As we do across the sites.

**Comment by grahambancroft** [comment]
I’m struggling to find an example of where we use .align-vertically without .equal-height, could you point me in the right direction.

**Comment by anthonydillon** [comment]
Code and QA ok but the documentation is missing. Can you update this please.

**Comment by anthonydillon** [comment]
What is the status of this PR?

**Comment by grahambancroft** [comment]
I’ve added align-vertically to the docs so this is ready for re-review

**Comment by anthonydillon** [comment]
Looks good thanks for the doc comments :+1:

**Pull request merged**
