### PR TITLE
Update local usage instructions in README to include @import method

### PR DESCRIPTION
**Pull request by barrymcgee**
## Done

Using this updated method should remove the conflict caused by moving from NPM 2 to NPM 3.

## QA

Read the new instructions, try them out and make sure they work.

## Details

Fixes: #364, #211

### CODE REVIEW

**Comment by barrymcgee** [comment]
@anthonydillon I've assigned you to review this as you're most familiar with the fix applied to Ubuntu Vanilla Theme.

**Comment by anthonydillon** [comment]
Sorry @barrymcgee missed this one. Is this branch still valid? https://github.com/ubuntudesign/vanilla-framework/pull/368

**Comment by barrymcgee** [comment]
@anthonydillon Yep, still valid..

**Comment by anthonydillon** [comment]
@barrymcgee You will have to reopen.

**Comment by barrymcgee** [comment]
Accidentally deleted this branch...

**Comment by barrymcgee** [comment]
@anthonydillon Now re-opened..

**Comment by anthonydillon** [comment]
Code and QA :+1:

**Pull request merged**
