### PR TITLE
Add helper classes

### PR DESCRIPTION
**Pull request by anthonydillon**
# Done
- Added all our helper classes to _helpers.scss
- Documented the helper mixins
- Added demos of the helpers to the bottom demo/index.html

## QA
- Lint and check no errors
- Check the demo works
- Check they are all documented in the docs

### CODE REVIEW

**Comment by deadlight** [comment]
Build error: "no mixin named vf-no-margin"

Lint error: "modules/_helpers.scss:421 [W] FinalNewline: Files should end with a trailing newline"

Also it looks like this can't merge cleanly... sorry.

**Comment by anthonydillon** [comment]
Fixed ... I think

**Comment by deadlight** [comment]
It all lints and the docs cover everything pretty clearly.

I strongly oppose the classes with pixel numbers in their names; as discussed fixing them to make them relative to the gutters or column sizes would be an improvement or just removing them entirely (as seems to be the plan).

But... :+1: from me for now

**Comment by anthonydillon** [comment]
Thanks Karl. I agree with you on the pixel classes. We work out a plan tomorrow.

**Pull request merged**
